/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"

int main(void)
{
	/*Configure GPIO*/
	// Set Bit 3 to enable GPIOB clock
	RCC->APB2ENR |= (1 << 3);

	// Make GPIOB Pin11 output
	GPIOB->CRH &= 0xFFFF0FFF;
	GPIOB->CRH |= 0x0000B000;

	/*Configure AF*/

	// Set Bit 0 to enable AF clock
	RCC->APB2ENR |= (1 << 0);
	// Use REMAP function to use PWM4 from TIM2 in B11
	AFIO->MAPR |= (3 << 8);

	/*Configure timer2*/

	// Enable clock access to timer2
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	TIM2->PSC = 0;
	TIM2->ARR = 100;

	TIM2->CCMR2 |=TIM_CCMR2_OC4M_2|TIM_CCMR2_OC4M_1;
	TIM2->CCER  |= TIM_CCER_CC4E;
	TIM2->CR1   |= TIM_CR1_CEN;

	while(1)
	{
		for (volatile int i=0;i<100;i++)
		{
			TIM2->CCR4=i;
			for (int j=0;j<10000;j++);
		}

		for (volatile int i=100;i>0;i--)
		{
			TIM2->CCR4=i;
			for (int j=0;j<10000;j++);
		}

	}

}
