/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"

int SysTick_TASK = 0;
void SysTick_Handler(void)
{
	// Do stuff
	SysTick_TASK = 1;
}
void setLEDs(uint8_t r, uint8_t g, uint8_t b)
{
    if (r) GPIOB->ODR |= (1 << 8);
    else GPIOB->ODR &= ~(1 << 8);

    if (g) GPIOB->ODR |= (1 << 10);
    else GPIOB->ODR &= ~(1 << 10);

    if (b) GPIOB->ODR |= (1 << 9);
    else GPIOB->ODR &= ~(1 << 9);
}


int main(void)
{
	/*
	 * Para habilitar o clock de cada periferico leia a secao 7.3.7.APB2 peripheral clock enable register (RCC_APB2ENR)
	 * Clock dos Perifericos
	 */

	//habilite para usa o GPIOB clock
	RCC->APB2ENR |= (1 << 3);


	/*
		 * Output
		 * Para habilita um pino como saida olhe a secaoo 9.2.2 Port configuration register high (GPIOx_CRH)
		 * LED
		 *
	*/
	//LED1
	//CNF8[3:2] = 00 e MODE8[1:0] = 10
	GPIOB->CRH &= 0xFFFFFF0; // binario - 11111111111111111111111111110000
	//habilita o bit [1]
	GPIOB->CRH |= (1<<1);  // binario - 11111111111111111111111111110010

	// Reset GPIOB Pin8
	GPIOB->ODR &= ~(1<<8);


	//LED2
	//CNF9[7:6] = 00 e MODE9[5:4] = 10
	GPIOB->CRH &= 0xFFFFF0F; // binario - 11111111111111111111111100001111
	//habilita o bit [5]
	GPIOB->CRH |= (1<<5); // binario - 11111111111111111111111100101111

	// Reset GPIOB Pin9
	GPIOB->ODR &= ~(1<<9);


	//LED3
	//CNF10[11:10] = 00 e MODE10[9:8] = 10
	GPIOB->CRH &= 0xFFFF0FF; // binario - 11111111111111111111000011111111
	//habilita o bit [5]
	GPIOB->CRH |= (1<<9); // binario - 11111111111111111111001011111111

	// Reset GPIOB Pin10
	GPIOB->ODR &= ~(1<<10);
    /* Loop forever */


	/*************>>>>>>> Systick <<<<<<<<************

	1. Create counter variable
	2. Configure the LOAD register to set the reload value.
	3. Set the VAL register to 0
	4. Set the CTRL register to enable SysTick and interrupt.
		4.1. Enable the SysTick clock to AHB/8
		4.2. Enable interrupt SysTick (SysTick IRQ)
		4.3. Enables the SysTick timer

	********************************************************/

	/*
	 * System Tick Configuration
	 * Initializes the System Timer and its interrupt, and starts the System Tick Timer.
     * Counter is in free running mode to generate periodic interrupts.
	 */
	uint32_t ticks = 8000000;
	/*
	 * O registrador de recarga (LOAD) do SysTick tem 24 bits de largura,
	 * o que significa que o valor máximo que ele pode conter é 0xFFFFFF
	 * (16.777.215 em decimal). Portanto, verificamos se ticks - 1 é menor
	 *  ou igual a 0xFFFFFF para garantir que o valor cabe no registrador.
	 */
	if ((ticks - 1UL) <= 0xFFFFFFUL)
	{
		 /* set reload register */
		SysTick->LOAD  = (uint32_t)(ticks - 1UL);

		/* set Priority for Systick Interrupt */
		//NVIC_SetPriority (SysTick_IRQn, (1UL << __NVIC_PRIO_BITS) - 1UL);

		//O registrador VAL é zerado para iniciar a contagem do SysTick a partir de zero.
		SysTick->VAL   = 0UL;			/* Load the SysTick Counter Value */


		SysTick->CTRL  = (0 << 2) |		// Enable the SysTick clock to AHB/8
						 (1 << 1) |	 	// Enable interrupt SysTick (SysTick IRQ)
						 (1 << 0);		// Enables the SysTick timer
	}


    uint8_t states[8][3] = {
        {0, 0, 0}, // Apagado
        {1, 0, 0}, // Vermelho
        {0, 1, 0}, // Verde
        {0, 0, 1}, // Azul
        {1, 1, 0}, // Amarelo
        {0, 1, 1}, // Ciano
        {1, 0, 1}, // Roxo
        {1, 1, 1}  // Branco
    };

    int currentState = 0;

    for(;;)
    {
        if (SysTick_TASK)
        {
            SysTick_TASK = 0;

            setLEDs(states[currentState][0], states[currentState][1], states[currentState][2]);

            currentState = (currentState + 1) % 8;
        }
    }


}
