/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"

/*
 * TIM2interrupt handler
 */
void TIM2_IRQHandler(void)
{
	if(TIM2->SR & TIM_SR_UIF)
	{
		GPIOB->ODR ^= (1 << 11);

		TIM2->SR &=~TIM_SR_UIF;
	}

}

int main(void)
{
	// Set Bit 3 to enable GPIOB clock
	RCC->APB2ENR |= (1 << 3);

	// Make GPIOB Pin11 output
	GPIOB->CRH &= 0xFFFF0FFF;
	GPIOB->CRH |= 0x00002000;

	// Reset GPIOB Pin11
	GPIOB->ODR &= ~(1 << 11);

	// Enable clock access to timer2
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	// Configure timer2
	TIM2->PSC = 8000-1; 	//8000000/8000 =1000 i.e. 1ms
	TIM2->ARR = 1000-1; 	//count up to 1000 which is 1 second

	/* Set UIE(Update interrupt enable) bit
	 * in TIMx DMA/Interrupt enable register (TIMx_DIER)
	 * to enable timer interrupt*/
	TIM2->DIER |= TIM_DIER_UIE;

	// Enable timer2 interrupt in NVIC
	NVIC_EnableIRQ(TIM2_IRQn);

	// Enable the timer
	TIM2->CR1 |= TIM_CR1_CEN;

	while(1)
	{

	}
}
