/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"

/*
 * EXTI0 external interrupt handler
 */
void EXTI0_IRQHandler(void)
{
	// Do stuff
	GPIOC->ODR ^= (1 << 13);
	// Clear pending
	EXTI->PR = (1 << 0);
}

/*
 * EXTI1 external interrupt handler
 */
void EXTI1_IRQHandler(void)
{
	// Do stuff
	GPIOC->ODR ^= (1 << 13);
	// Clear pending
	EXTI->PR = (1 << 1);
}

int main(void)
{
	// Set Bit 3 to enable GPIOB clock
	RCC->APB2ENR |= (1 << 3);
	// Set Bit 4 to enable GPIOC clock
	RCC->APB2ENR |= (1 << 4);

	// Make GPIOB Pin0 and Pin1 input
	GPIOB->CRL &= 0xFFFFFF00;
	GPIOB->CRL |= 0x00000088;
	//Enable GPIO Pin0 and Pin1 pull-up
	GPIOB->ODR = 0x00000003;

	// Make GPIOE Pin13 output
	GPIOC->CRH &= 0xFF0FFFFF;
	GPIOC->CRH |= 0x00200000;

	// Reset GPIOC Pin13
	GPIOC->ODR &= ~(1 << 13);

	// Since we will use Alternate Function (EXTI) we need to enable the
	//   clock for that module. Bit0 in RCC APB2ENR register
	RCC->APB2ENR |= (1 << 0); // AFIO Clock enable

	// EXTI0 can be configured for each GPIO module.
	//   EXTICR1: 0b XXXX XXXX XXXX 0001
	//               pin3 pin2 pin1 pin0
	//
	//   Writing a 0b0001 to pin0 location ties PB0 to EXT0
	AFIO->EXTICR[0] |= AFIO_EXTICR1_EXTI0_PB; // Tie PB0 to EXTI0

	// EXTI1 can be configured for each GPIO module.
	//   EXTICR1: 0b XXXX XXXX 0001 XXXX
	//               pin3 pin2 pin1 pin0
	//
	//   Writing a 0b0001 to pin1 location ties PB1 to EXT1
	AFIO->EXTICR[0] |= AFIO_EXTICR1_EXTI1_PB; // Tie PB1 to EXTI1

	// Next we choose either falling edge trigger (FTSR) or falling edge trigger (FTSR)
	EXTI->FTSR |= 0x00001;   // Enable falling edge trigger on EXTI0
	EXTI->FTSR |= 0x00002;   // Enable falling edge trigger on EXTI1

	// We mask the used external interrupt numbers.
	EXTI->IMR |= 0x00001;    // Mask EXTI0
	EXTI->IMR |= 0x00002;    // Mask EXTI1

	// Set Prioirity for each interrupt request
	// STM32F103 supports 4-bit priority level (highest 4-bits are implemented)
	NVIC_SetPriority(EXTI0_IRQn,0x10); // Priority level 1
	NVIC_SetPriority(EXTI1_IRQn,0x20); // Priority level 2

	// Enable EXTI0 interrupt on NVIC
	NVIC_EnableIRQ(EXTI0_IRQn);
	// Enable EXTI1 interrupt on NVIC
	NVIC_EnableIRQ(EXTI1_IRQn);

	__enable_irq();	//NECESSARY IN THIS CODE??? - WHY ???

	while(1)
	{

	}
}
