/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



int main(void)
{
	/*Seta o clock no barramento APB2, para usar o GPIOC */
	uint32_t *pRCC_APB2ENR = (uint32_t*)0x40021018;

	/*
	 * GPIO
	 */
	// GPIOC
	// Saida
	// Seta o GPIOC para high
	uint32_t *pGPIOC_HIGH = (uint32_t*)0x40011004;
	// Seta o GPIOC como saida (LED)
	uint32_t *pGPIOC_OUT = (uint32_t*)0x4001100C;

	// GPIOA
	// Entrada
	// Seta o GPIOA para low
	uint32_t *pGPIOA_LOW = (uint32_t*)0x40010800;
	// Seta o GPIOA como entrada (botao)
	uint32_t *pGPIOA_INT = (uint32_t*)0x40010808;


	//1.Seta o clock para o GPIOC
	*pRCC_APB2ENR |= (1 << 4);
	//1.Seta o clock para o GPIOA
	*pRCC_APB2ENR |= (1 << 2);

	/*
	 * LEDS
	*/
	//  LED 1
	//CNF13[23:22] = 00 e MODE13[21:20] = 10
	//2a. Reseta os bits [23:20]
	*pGPIOC_HIGH &= ~(15 << 20);
	//2b. Seta o bit [21]
	*pGPIOC_HIGH |= (1 << 21);

	// LED 2
	//CNF14[27:26] = 00 e MODE14[25:24] = 10
	//2a. Reseta os bits [27:24]
	*pGPIOC_HIGH &= ~(15 << 24);
	//2b. Seta o bit [25]
	*pGPIOC_HIGH |= (1 << 25);

	// LED 3
	//CNF12[31:30] = 00 e MODE12[29:28] = 10
	//2a. Reseta os bits [19:16]
	*pGPIOC_HIGH &= ~(15 << 28);
	//2b. Seta o bit [29]
	*pGPIOC_HIGH |= (1 << 29);




	/*
	 * Botoes
	*/
	//Botao 1
	//CNF0[3:2] = 01 e MODE0[1:0] = 00
	//2a. Reseta os bits [3:0]
	*pGPIOA_LOW &= ~(15 << 0);
	//2b. Seta o bit [2]
	*pGPIOA_LOW |= (1 << 2);

	//Botao 2
	//CNF1[7:6] = 01 e MODE1[5:4] = 00
	//2a. Reseta os bits [7:4]
	*pGPIOA_LOW &= ~(15 << 4);
	//2b. Seta o bit [6]
	*pGPIOA_LOW |= (1 << 6);

	//Botao 2
	//CNF2[11:10] = 01 e MODE2[9:8] = 00
	//2a. Reseta os bits [9:8]
	*pGPIOA_LOW &= ~(15 << 8);
	//2b. Seta o bit [10]
	*pGPIOA_LOW |= (1 << 10);




	for(;;)
	{
		uint8_t b1 = (uint8_t)(*pGPIOA_INT & 0x1);
		if(b1){
			*pGPIOC_OUT |= (1<< 13);
		}else{
			*pGPIOC_OUT &= ~(1<< 13);
		}

		uint8_t b2 = (uint8_t)(*pGPIOA_INT & 0x2);
		if(b2){
				*pGPIOC_OUT |= (1<< 14);
		}else{
				*pGPIOC_OUT &= ~(1<< 14);
		}
		uint8_t b3 = (uint8_t)(*pGPIOA_INT & 0x4);
		if(b3){
				*pGPIOC_OUT |= (1<< 15);
		}else{
				*pGPIOC_OUT &= ~(1<< 15);
		}
	}
}

